version: '2'
services:
  ssh-server:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "ssh-server"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      1-network:
        ipv4_address: 10.10.10.2
      2-network:
        ipv4_address: 10.11.11.2
    image: gitlab.cs.pub.ro:5050/uso/uso-lab/lab09-ssh-server
    cap_add:
      - ALL
  remote:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "remote"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      1-network:
        ipv4_address: 10.10.10.3
    image: gitlab.cs.pub.ro:5050/uso/uso-lab/lab09-remote
    cap_add:
      - ALL
  local:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "local"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      2-network:
        ipv4_address: 10.11.11.3
    image: gitlab.cs.pub.ro:5050/uso/uso-lab/lab09-local
    cap_add:
      - ALL
  dropbox:
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    hostname: "dropbox"
    networks:
      1-network:
        ipv4_address: 10.10.10.4
    image: gitlab.cs.pub.ro:5050/uso/uso-lab/lab09-dropbox
    cap_add:
      - ALL
  dhcp:
    privileged: true
    image: networkboot/dhcpd
    networks:
      1-network:
        ipv4_address: 10.10.10.100
      2-network:
        ipv4_address: 10.11.11.100
    volumes:
      - ./dhcp/data:/data
networks:
  1-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.253
    driver_opts:
      com.docker.network.bridge.name: br1
  2-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.11.0/24
          gateway: 10.11.11.253
    driver_opts:
      com.docker.network.bridge.name: br2
