version: '2'
services:
  tom:
    user: "${UID}:${GID}"
    container_name: lab-container_tom_1
    privileged: true
    tty: true
    hostname: "tom"
    networks:
      1-network:
        ipv4_address: 10.10.10.2
      2-network:
        ipv4_address: 11.11.11.2
      3-network:
        ipv4_address: 12.12.12.2
    build:
      context: ./tom/
      dockerfile: ./Dockerfile
    cap_add:
      - ALL
  jerry:
    user: "${UID}:${GID}"
    container_name: lab-container_jerry_1
    privileged: true
    tty: true
    hostname: "jerry"
    networks:
      1-network:
        ipv4_address: 10.10.10.3
      2-network:
        ipv4_address: 11.11.11.3
      3-network:
        ipv4_address: 12.12.12.3
    build:
      context: ./jerry/
      dockerfile: ./Dockerfile
    cap_add:
      - ALL
  dhcp:
    privileged: true
    container_name: lab-container_dhcp_1
    image: networkboot/dhcpd
    hostname: "dhcp"
    networks:
      1-network:
        ipv4_address: 10.10.10.100
      2-network:
        ipv4_address: 11.11.11.100
      3-network:
        ipv4_address: 12.12.12.100
    volumes:
      - ./dhcp/data:/data
networks:
  1-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.253
    driver_opts:
      com.docker.network.bridge.name: br1
      icc: "true"
  2-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
          gateway: 11.11.11.253
    driver_opts:
      com.docker.network.bridge.name: br2
      icc: "true"
  3-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 12.12.12.0/24
          gateway: 12.12.12.253
    driver_opts:
      com.docker.network.bridge.name: br3
      icc: "true"
